- request.js
When using the AWS API Gateway custom Authorizer, AWS adds the property "requestContext" to the event.  This implementation adds this property to the Request class to avoid that it's being lost.
The requestContext property could then be used by the middle ware to check the principalId (or more)  added by AWS into requestContext.authorizer.principalId.
More info:
[AWS custom authenticator context](https://docs.aws.amazon.com/apigateway/latest/developerguide/use-custom-authorizer.html
)
section: Create an API Gateway Custom Authorizer Lambda Function:
> For the Lambda proxy integration, API Gateway passes the context object from a custom authorizer directly to the backend Lambda function as part of the input event. You can retrieve the context key-value pairs in the Lambda function by …
> Add the requestContext from AWS to the Request class

- index.d.ts
- package-lock.json
- package.json
Closes #28. 
Since this project uses "Lambda" types for some things, for example `event` and `context`, I added `@types/aws-lambda` as a `devDependency`. My reasoning being anyone using TypeScript with Lambda should/would already have that package installed. I suppose we could add it to `peerDependencies`, but that would be annoying for non-TS users.
I still have a bit of cleanup to do, any issues/feedback is most certainly welcome 👍
> Add TypeScript type definitions

- package.json
Currently the types are unusable since they don't get included when publishing to NPM 😅 
This PR fixes the issue by adding the types to the `files` array in `package.json`.
> Add types to npm tarball

- index.d.ts
- package-lock.json
This PR aims to improve the type declarations to more accurately reflect the documentation in the README as well as allow compilation in strict mode.
It also includes an updated package-lock.json file as a result of me simply running `npm install`. The only differences in that file seem to be values used by newer versions of NPM.
> Improve Type Declarations

- lib/request.js
- test/requests.js
- test/sample-event-consoletest1.json
When using the API Gateway's "Test" feature, lambda-api returns:
`{ error: 'Cannot convert undefined or null to object' }`
due to `multiValueHeaders` being passed as `null` by the API Gateway Console.
I've added a test case and a sample event generated by the console. Request parser is checking whether `multiValueHeaders` is not null.
> Added support for API Gateway Console Test event

- index.d.ts
- index.js
- test/headers.js
This could possibly solve #109, we are testing this implementation in our own stack right now.
It should allow you to pass a whitelist to lambdaApi as such:
```
const api = lambdaApi({
errorHeaderWhitelist: [
"Access-Control-Allow-Origin"
]
})
```
> #109 Implement a whitelist for headers as an option to LambdaAPI

- lib/request.js
fix: https://github.com/jeremydaly/lambda-api/issues/123
> Buffer.from '' if this.app._event.body is falsy

- index.js
- test/register.js
The test case demonstrates how the [bug](https://github.com/jeremydaly/lambda-api/issues/121) manifests.
What the change does: Running `Array.prototype.slice(0, -0)` will effectively slice away everything from start to end; so let's only clean up when there is something to clean.
> Fix and test for #121

- README.md
- index.js
It's been a while, but I've bumped into this issue again when using default TypeScript compiler settings (`"esModuleInterop": false`).
Current `index.d.ts` suggests that the initialising function is a default export:
```typescript
declare function createAPI(options?: Options): API;
export default createAPI;
```
but this wasn't the case in index.js
This PR adds that default export without affecting current users.
"TypeScript Example" in README has been updated with a complete lambda-api example (matching JS example) and aws-lambda type imports. It should just work after copy/paste.
> Add default export to match TypeScript definition #110

- index.d.ts
Proposed types for missing api and attributes:
1. api.register(routes, options) where:
a) routes - is a function that registers new handlers e.g.: `(api, opts) => { api.get('/product', handler_v1) }`
b) options (optional) - object which may contain a "prefix" string attribute.
2. api.routes() which:
a) always returns `string[][]`, when called as: `routes()`, `routes(false)`
b) always returns `void`, when called as: `routes(true)` (console log output instead)
3. req.namespace which:
a) is an `App` Object containing `any` object or module for given `string` namespace key, registered against the API instance using the app(...) method.
b) unlike the initial definition, `interface App` does not contain a `HandlerFunction`.
Based on sample usage:
`let userInfo = …
> TypeScript support for api.register/routes, req.namespace (issue #137)

- README.md
- index.d.ts
- index.js
- lib/compression.js
- lib/response.js
- test/responses.js
Automatically compress responses based on the `Accept-Encoding` header:
```javascript
const api = require('lambda-api')({
compression: true
})
```
> Automatic Compression

- README.md
- __tests__/responses.unit.js
- index.js
- lib/compression.js
- lib/response.js
- Disables Brotli compression by default due to its excessive CPU usage.
- Provides an API to opt-in to Brotli compression
> Compression - Disable Brotli by Default

- __tests__/errorHandling.unit.js
- lib/errors.js
- package-lock.json
> Preserve error names even if code is bundled and class names are changed to avoid duplicates

- index.d.ts
Docs show that we could add a second argument in the logger, it's working fine in JS but in TS the typing was only accepting string arguments
> fix: logger function should accept second arguments

- __tests__/sampling.unit.js
- lib/logger.js
fixes #214
Let me know if you'd like the fix reworking at all, I'm happy to do so (or happy for you to fix it in your own commit, it's a very simple fix!).
Thanks again for writing & maintaining this great library.
> fix(logger): resolve 1st entry in log sampling rules cfg is unused #215

- index.d.ts
Currently the use function allows for inputs to be either Middleware or ErrorHandlingMiddleware. However, the typescript type requires the list of arguments to be only Middleware or only ErrorHandlingMiddleware. I.e. you couldn't call api.use with both error middleware and normal middleware. This pr brings the typescript type back into line with code expectation.
Code Section in question:
https://github.com/jeremydaly/lambda-api/blob/c1fe83e53d56eb23c4ef755c01bf1ebc07a7c342/index.js#L355-L383
> fix(types): resolve use func not allowing to mix middlewares

- index.d.ts
None is a valid value for SameSite and useful in certain cases.
> feat(cookies/types): add 'None' as a valid sameSite value

- index.d.ts
It is valid to chain `response.type('application/xml').status(200).send(xml)` because the `type` function returns an instance of **this**. This change correct the `index.d.ts` typing description from incorrectly returning **void** to correctly returning **this** as apparent from `lib/response.js` .
> fix(Response/type): resolve void returned instead of this

- README.md
This fixes a minor typo in the link to the mimemap.js file in the README.md
> fix(docs): bad link mindmap->mimemap

- __tests__/download.unit.js
- __tests__/getLink.unit.js
- __tests__/responses.unit.js
- __tests__/sendFile.unit.js
- lib/s3-service.js
- package-lock.json
- package.json
This should most likely be released as a breaking version change
> feat(s3-service)!: move to AWS-SDK v3

- .github/workflows/pull-request.yml
- README.md
- package-lock.json
- package.json
- related to issue https://github.com/jeremydaly/lambda-api/issues/229
- ran `prettier` in code to fix failing ci https://github.com/jeremydaly/lambda-api/actions/runs/4388737872/jobs/7685568423
cc @naorpeled
> fix(dependencies): aws sdk v3 packages are dependencies not devDependencies

- README.md
- __tests__/sendFile.unit.js
- index.js
- lib/s3-service.js
User may want to change the config of the client for s3. One example of this is during local dev, to change endpoint etc.
I think the only way to currently do this, is to import the client from lambda-api/lib/s3-service.js and override it?
I think it might be a nicer user experience to be able to provide the config on api init. 😄
> User Provided S3 Config

- __tests__/sendFile.unit.js
- index.js
- lib/response.js
This lazy loads the S3 client so it no longer adds ~100 ms to coldstarts if you minify your bundle and don't use S3.  If you are using the on disk version of `client-s3`, it reduces coldstarts by ~300ms. By lazy loading you can also omit `client-s3` in a minified bundle if you don't use it reducing the bundled package size by over 340 KB.  While making this change I noticed that the call to `setConfig` when using a custom s3 client was in the `run` method causing a new S3Client to be created for every request.  I moved the `setConfig` call to the `createAPI` method so the same S3 client is reused across requests.
> (feat): Lazy load S3 client

- index.d.ts
The `Response` type declaration is lacking the definition for `multiValueHeaders`
> Add multiValueHeaders type to Request

- __tests__/headers.unit.js
- index.d.ts
- lib/response.js
> feat(Response): add setHeader as header fn alias

- __tests__/cookies.unit.js
- lib/request.js
Change:
- Addresses the invalid cookie parse when the cookie value contains a "=".
- Add a test to ensure the cookie parsing logic supports the entire ASCII character set, minus semi-colon, comma, backslash, percent, and white space.
Closes #269 
Note:
I stumbled on another issue regarding cookie parsing while working on this PR. I opened an issue here: https://github.com/jeremydaly/lambda-api/issues/270
> fix: invalid cookie parsing for the "=" character

- index.d.ts
This PR updates the typing of `Request#multiValueHeaders` to make the header values arrays.
Closes #274
> Correct type of multiValueHeaders

- index.d.ts
This library has ALB integration but current TypeScript types do not reflect this.
For example the `API#run`  method does not accept an `ALBEvent` type meaning that if someone wants to be extremely correct the fix is something like the following:
```ts
async function handler(event: ALBEvent, context: Context): Promise<any> {
return api.run(event as unknown as APIGatewayProxyEvent, context);
}
```
This PR aims to fix this.
> Add TypeScript support for ALB related types

- README.md
- __tests__/errorHandling.unit.js
- index.d.ts
- index.js
- index.test-d.ts
- lib/errors.js
- lib/response.js
> fix(error-handling-middleware): handle str error as ApiError
